version: '3.7'

services:

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: User
      POSTGRES_DB: car-rent
    container_name: car-rent-db
    ports:
      - 5432:5432